### ISSUE TITLE
Some problems about the prediction of occlusion

### ISSUE THREAD

**Issue by Ecalpal** [anuragranj/back2future.pytorch#4]
Thanks for your great job!

I try to binary the occlusion by using **nn.sigmoid** and **np.round**, but it doesn't seem to be the right way.

I want to know what is the right way to visualize occlusion?
Or can you send to me the files which occlusion visualization on KITTI, Sintel and Middlebury if you have them? 
I shall be very grateful.:blush:

**Comment by JJanai** [comment]
Hi,

the two-dimensional occlusion variables lie between [0,1] and sum up to one.
The first dimension represents past occlusions while the second dimension represents future occlusions. Since we have continuous variables, we can have states that are in between our three occlusion states (partly visible).

However, you can visualize the three occlusion states by thresholding the occlusion variables in the following way: We have a past occlusion / future occlusion if the first dimension / second dimension is larger than 2/3 otherwise the pixel is visible.

Best,
Joel

**Comment by Ecalpal** [comment]
> Hi,
> 
> the two-dimensional occlusion variables lie between [0,1] and sum up to one.
> The first dimension represents past occlusions while the second dimension represents future occlusions. Since we have continuous variables, we can have states that are in between our three occlusion states (partly visible).
> 
> However, you can visualize the three occlusion states by thresholding the occlusion variables in the following way: We have a past occlusion / future occlusion if the first dimension / second dimension is larger than 2/3 otherwise the pixel is visible.
> 
> Best,
> Joel

I'm still a little confused.
https://github.com/anuragranj/back2future.pytorch/blob/a3b619a9eb11c91866160565a8593dda690c2da9/test_back2future.py#L49
The network output a tensor named occ, which size is (1,2,382,1280), occ[0][0] represents the backward occlusion and occ[0][1] represents the forward occlusion. Have I understood correctly? 

 Can you use pseudocode to describe the process of binarization? :flushed:
